# Generated by Django 4.2.4 on 2023-10-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_date_creditcard_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
